added scrot-options - changed conky to use sed for transparency control.

diff --git a/config/includes.chroot_after_packages/usr/local/bin/dk-installer b/config/includes.chroot_after_packages/usr/local/bin/dk-installer
--- a/config/includes.chroot_after_packages/usr/local/bin/dk-installer
+++ b/config/includes.chroot_after_packages/usr/local/bin/dk-installer
@@ -27,14 +27,15 @@ read -p "   [0;33mdk WM Installer.[0m
    -------------------------------------------------------------[0m
       
    Or close this terminal window to quit the install." ;
+## Check for internet connection
    if : >/dev/tcp/8.8.8.8/53; then
 echo ""
 cd /tmp/ &&
-sudo apt update && sudo apt install sxhkd build-essential polybar libxcb-randr0-dev libxcb-util-dev libxcb-icccm4-dev libxcb-cursor-dev libxcb-keysyms1-dev &&
+curl -fSL https://bitbucket.org/natemaia/dk/get/v1.9.zip -o dk.zip &&
 # For the latest - possibly unstable, uncomment the below line and comment the curl line.
 #git clone https://bitbucket.org/natemaia/dk.git &&
-curl -fSL https://bitbucket.org/natemaia/dk/get/v1.9.zip -o dk.zip &&
 unzip dk.zip &&
+sudo apt update && sudo apt install sxhkd build-essential polybar libxcb-randr0-dev libxcb-util-dev libxcb-icccm4-dev libxcb-cursor-dev libxcb-keysyms1-dev &&
 cd natemaia-dk-* &&
 make &&
 sudo make install &&
@@ -42,20 +43,35 @@ cp -r /usr/share/lilidog/extras/dk ~/.config &&
 cp -r /usr/share/lilidog/extras/polybar ~/.config &&
 rm -r /tmp/natemaia-dk-*
 rm -r /tmp/dk.zip
+# For .xsessionrc use:
+if ! grep -Fq "DKWM" ~/.xsessionrc; then
+{
+echo ''
+echo '## Uncomment to use DKWM as default:'
+echo '#exec dk'
+echo ''
+echo '## Uncomment to use openbox as default: (may not be required)'
+echo '#exec openbox-session'
+} >> ~/.xsessionrc
+fi
 echo ""
 echo "----------------------------------------------------------------------"
 echo ""
 echo "[0;32mAll Finished!.
-New Login entry for 'dk' added. Logout and choose dk to change WM's.
+
+Logout and choose dk to change WM's if lightdm is installed.
+If lightdm is not installed, uncomment the entry in ~/.xsessionrc to use dkwm.
+
 To uninstall, run: 'dk-uninstaller' in a terminal.[0m"
 echo "" 
 echo "----------------------------------------------------------------------"
 else
 echo ""
- echo "   [0;31m-----------------------------------------------------[0m"
+ echo "   [0;31m-------------------------------------------------------"
  echo ""
- echo "   [0;33mNo Internet connection. Please connect and try again.[0m"
+ echo "   No Internet connection. Please connect and try again."
  echo ""
- echo "   [0;31m-----------------------------------------------------[0m"
+ echo "   -------------------------------------------------------[0m"
 echo ""
 fi
+read -n1 -p " Press any key to quit this dialog ... "
